# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.__version__

'1.26.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
''' In numpy a null vector is one that contains zero, this is logical because all elements of an array must
have thesame datatypes so if we have some integer we can represent null values by zers'''
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
#The memory size of an array is the number of elements in the array
arr = np.arange(10).reshape(2,5)
np.size(arr)

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
help(np.add)

# we can use: python -c "import numpy as np; print(help(np.add))"

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
arr =  np.zeros(10) #create null vector of size 10
arr[5] = 1 # set 5th element to 1
print(arr)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
arr = np.arange(10, 50) #specify vector range as arguement (start, end)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr = arr[::-1] # reverse the array
print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
arr = np.arange(0, 9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
arr = np.array([1, 2, 0, 0, 4, 0])
np.where(arr > 0)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.random((3,3,3))

#other ways to do it:

# np.random.randint(0,10, (3, 4, 2))  # creates a 3 by 4 by 2 array with random numbers between 0 and 10
# np.random.rand(27).reshape(3,3,3) here we created an array of certain size containing random numbers and resized it to a 3 by 3 array

array([[[0.29049885, 0.13593484, 0.87886332],
        [0.34897545, 0.43432818, 0.08418446],
        [0.1774722 , 0.49355055, 0.40447269]],

       [[0.42213887, 0.49708218, 0.14595296],
        [0.66223138, 0.47775613, 0.32985838],
        [0.07194318, 0.22896082, 0.1178685 ]],

       [[0.1898518 , 0.98834612, 0.07250158],
        [0.25367794, 0.33026473, 0.89409051],
        [0.13199125, 0.58234855, 0.24533217]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [40]:
arr = np.random.randint(0, 10, (10,10))
print("minimum element: ", np.min(arr))
print("maximum element: ", np.max(arr))

minimum element:  0
maximum element:  9


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [42]:
arr = np.random.randn(30)
print("mean of arr is: ", np.mean(arr))

mean of arr is:  0.06990124413755928


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
#  solution 1
arr = np.zeros((3, 4))
border = [-1, 0]
#use  a for loop
for i in border:
    arr[i,:] = 1
    arr[:,i] = 1
print(arr)

#this method is inefficient as some redudancy occurs in the loop process
# C:\Users\ELIAS IFENAIKE\Desktop\CodeLearn\DataScience


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [5]:
# solution 2
import numpy as np

arr = np.zeros((3, 4))

# Directly modify the first and last rows and columns
arr[0, :] = 1         # First row
arr[-1, :] = 1        # Last row
arr[:, 0] = 1         # First column
arr[:, -1] = 1        # Last column

print(arr)


[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [19]:
#using np.ones()
arr = np.ones((3, 4))
arr[1:-1, 1: -1] = 0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
rows, col = arr.shape[0] + 2,  arr.shape[1] +  2
new_arr =  np.zeros((rows, col))
new_arr[1:-1, 1:-1] = arr
print(new_arr)


[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
# second method using the pad method
np.pad(arr, pad_width=1, mode='constant', constant_values=0)


array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# nan -> This is simply because nan is not a number
# False -> np.nan always creates a new object. The nan that you're testing against is a pre-existing object that will never be the same ID as a newly created one. 
# False -> simply because nan is not a number
# np.nan -> one of the properties if nan
# True -> when you are comparing, we check if an np.nan object exisit in the set. That is why we get True
# False -> This is because python does not store floating point properly. 0.3 is probably stored as 0.300000004

nan

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
arr = np.zeros((5, 5))
for i in range(1, len(arr)):
    arr[i,i-1] = i
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [54]:
arr = np.zeros((8,8))
for i in range(len(arr)):
    if i%2 == 0:
        arr[i,::2] = 1
    else:
        arr[i,1::2] = 1 # or do arr[i::-2]
print(arr)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [49]:
# we can find the linear index of the 100th element and covert that to the 3 dimensional index
linear_idx = 99 # 100 element in a linear array is at 99th index
first_index =  99// (7 * 8)
second_index = (99 % (7 * 8)) // 8
third_index = (7 * 8) // 8
print((first_index, second_index, third_index))

(1, 5, 7)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
# Create a two-dimensional array
arr = np.array([[1, 0], [0, 1]])

# Repeat the array
checker_board = np.tile(arr, (4, 4))
print(checker_board)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [14]:
np.random.seed(1234)
arr = np.random.random((5, 5))

#Vector nomalization
nom_arr = arr / np.linalg.det(arr)
print(nom_arr)

print(" \n \n")

#Z score normalization
Z_norm_arr =  (arr -  arr.mean()) / arr.std()
print(Z_norm_arr)

print(" \n \n")

# min max normalization
min_max_nom = (arr - arr.min()) / (arr.max() - arr.min())
print(min_max_nom)


[[ 3.733333   12.12691035  8.53272819 15.30917676 15.20424907]
 [ 5.31371079  5.38918175 15.63108007 18.67723233 17.07475771]
 [ 6.97501491  9.76601401 13.32290128 13.89286567  7.21738371]
 [10.93952723  9.80671665  0.26839158 15.06488832 17.20552915]
 [ 7.11280699 11.99606023  1.469424    7.18957177 18.18991612]]
 
 

[[-1.34928699  0.27720685 -0.41926795  0.89386129  0.87352857]
 [-1.04304394 -1.0284193   0.95623919  1.54651765  1.23599271]
 [-0.72111911 -0.18028382  0.50896404  0.61941082 -0.67415328]
 [ 0.04711767 -0.17239653 -2.02071774  0.84652347  1.26133339]
 [-0.69441799  0.25185093 -1.78798362 -0.67954263  1.45208631]]
 
 

[[0.1882216  0.64417521 0.44893303 0.81704141 0.81134156]
 [0.27407045 0.27817016 0.83452775 1.         0.91295081]
 [0.36431535 0.51592724 0.7091435  0.74010495 0.37748125]
 [0.57967451 0.51813828 0.         0.80377124 0.92005454]
 [0.37180046 0.6370672  0.06524215 0.37597045 0.97352814]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [19]:
# An UnsignedByte is like a Byte , but its values range from 0 to 255 instead of -128 to 127.
import numpy as np

# Define the custom dtype for RGBA (four unsigned bytes)
color_dtype = np.dtype([('R', np.uint8),  # Red component (0-255)
                        ('G', np.uint8),  # Green component (0-255)
                        ('B', np.uint8),  # Blue component (0-255)
                        ('A', np.uint8)])  # Alpha component (0-255)

# Create a color using the custom dtype
color = np.array((255, 0, 0, 255), dtype=color_dtype)  # Red with full opacity (RGBA: (255, 0, 0, 255))

# verify color dtypes
color.dtype


dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [20]:
np.random.seed(0)
mat_1 = np.random.randint(0, 10, (5, 3))
mat_2 = np.random.randint(0, 10, (3, 2))
prod = np.dot(mat_1, mat_2)
print(prod)


[[ 33  50]
 [ 76 122]
 [ 55  71]
 [ 79 114]
 [105 125]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
arr = np.array([2, 4, 6, 11, 1])
mask = (arr < 8) & (arr > 3)
arr[mask] = -arr[mask]
print(arr)

[ 2 -4 -6 11  1]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [31]:
# print(sum(range(5),-1)) output is 9 : 0 + 1 +2 + 3 + 4

# from numpy import *
# print(sum(range(5),-1)) output is 10, because in numpy sum function, the -1 is taken as the axis element

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [32]:
#  Legal: this is because Z**Z it does z to the power of z element-wise in numpy
#  Legal: Bitshift operation element-wise
#  Illegal: <- is not a comparison operator and it doesn't even exist
#  Legal: multiplies Z by complex number j
#  Legal: divides Z by 1 twice, element-wise
#  Legal: It'll return False since the comparison is false

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [41]:
# nan because 0/0 is undefined or not a number
# 0 # yh remainder from division is 0 even if division gives undefined
# A large negative number (most likely representing negative infinity)

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
# To round a float away from zero means to round positive numbers up and negative numbers down
arr = np.array([-1.5, 3.5, -2.4, 2.3])
np.round(arr + np.sign(arr)* 0.5) # we added the np.sign(arr)*0.5 to ensure numbers like 1.2 are rounded up to 2 

array([-2.,  4., -3.,  3.])

#### 30. How to find common values between two arrays? (★☆☆)

In [47]:
arr_1 = np.array([3, 4, 1, 2])
arr_2 = np.array([5, 6, 3, 1])

np.intersect1d(arr_1, arr_2)

array([1, 3])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [21]:
import warnings
warnings.filterwarnings("ignore")



#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [53]:
# no the first returns a domain error while emath considers complex domain 

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [27]:
print(np.datetime64("today"))
print(np.datetime64("today") - np.timedelta64(1))
print(np.datetime64("today") + np.timedelta64(1))


2025-04-11
2025-04-10
2025-04-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [29]:
np.arange("2016-07-01", "2016-08-01", dtype= "datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)